export interface Pokemon {
  alternate_form: string;
  field_shadow_pokemon_: "Off" | "On";
  is_mega: "Off" | "On";
  number: string;
  sta: string;
  atk: string;
  def: string;
  cp: string;
  field_pokemon_generation: string;
  field_pokemon_type: string;
  title_1: string;
  uri: string;
  field_primary_moves: string;
  field_secondary_moves: string;
  nid: string;
  field_legacy_charge_moves: string;
  field_legacy_quick_moves: string;
  field_evolutions: string;
  catch_rate: string;
  field_flee_rate: string;
  quick_exclusive_moves: string;
  charge_exclusive_moves: string;
  second_charge_cost: string;
  pokemon_image_small: string;
  title: string;
  lvl20: string;
  lvl30: string;
  lvl40: string;
  purification_candy: string;
  purification_dust: string;
  elite_charge_moves: string;
  elite_fast_moves: string;
  purified_charge_moves: string;
  purified_fast_moves: string;
  pokemon_thumbnail: string;
  lvl35: string;
  rating_gl: string;
  rating_ml: string;
  rating_ul: string;
  buddy: string;
  evo_requirements: string;
  unavailable: "Off" | "On";
}
